accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

plands/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

plands/views.py
from django.shortcuts import render, redirect
from django.contrib import auth

def index(request):

    return render(request, 'index.html')

accounts/templates/accounts/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}

        <!-- 필드 오류를 출력한다. -->
        <div>
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}
        <!-- 넌필드 오류를 출력한다. -->
        <div>
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
    <h3>로그인</h3>

    <form method="POST" action = "{% url 'accounts:login' %}">
        {% csrf_token %}
        {% include 'accounts/form_errors.html' %} <!-- 로그인 실패 시 로그인 실패 원인 출력-->
        
        <div>
            <label>사용자 ID</label>
            <input type="text" name="username" id="username">
        </div>
        <div>
            <label>비밀번호</label>
            <input type="text" name="password" id="password">
        </div>
        <button type="submit">로그인</button>
    </form>
    
{% endblock %}

plands/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
  </head>

  <body>
    <span>네브바야 ----> </span>
    <a href="{% url 'index' %}">인덱스 페이지</a>
    <span>|</span>

    {% if user.is_authenticated %} 
        <a href="{% url 'accounts:logout' %}">{{ user.username }}님 로그아웃</a>
        <span>|</span>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>    
    {% endif %}

    
    {% block content %}{% endblock %}
  </body>

</html>

plands/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <h3>인덱스 페이지</h3>

  {% if user.is_authenticated %}
  안녕하세요, {{user.username}} 님!
  {% else %}
  로그인을 해주세요!!!!!
  {% endif %}

  {% comment %} <a href="{% url 'accounts:login' %}"> 로그인 </a> {% endcomment %}
{% endblock %}